In [9]:
# Set up API keys
api_key = "97F7QmwC4ENkgVzeS0wg9xQx4"
api_key_secret = "HipmVUw35RvPffvNWwYe92QYHBjcYNrmrCLTZxcFeOZlxMzvLV"
access_token = "1198581859430682625-MLbPthrrFCCEughdHXfWLnusQeljN6"
access_token_secret = "Pz9BeuzDGzFMVg43cLIPdylAimkx9ojBlwffIGkcCqjJG"

In [3]:
import tweepy
import csv
import pandas as pd

In [4]:
# Twiterr handles of selected left-leaning US/UK publishing houses 
jacobin_handle = "jacobinmag"
verso_handle = "versobooks"
haymarket_handle = "haymarketbooks"
tribune_handle = "tribunemagazine"

In [5]:
# reference --> https://gist.github.com/yanofsky/5436496

def get_all_tweets(screen_name):
    # Because of the limit, this function only allows for 3240 tweets to be collected
    
    # Authorize twitter and initialize tweepy
    auth = tweepy.OAuthHandler(api_key, api_key_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth)
    
    # Create empty list to hold all tweets
    alltweets = []  
    
    # maake  request for  recent tweets (200 is the maximum allowed for count, extended allows for full 280 chars)
    new_tweets = api.user_timeline(screen_name = screen_name, count=200, tweet_mode="extended")
    
    # save tweets
    alltweets.extend(new_tweets)
    
    # save the id of the oldest tweet less one
    oldest = alltweets[-1].id - 1
    
    # keep grabbing tweets until there are no tweets left to grab
    while len(new_tweets) > 0:
        print(f"getting tweets before {oldest}")
        
        #all subsiquent requests use the max_id param to prevent duplicates
        new_tweets = api.user_timeline(screen_name = screen_name,count=200,max_id=oldest, tweet_mode="extended")
        
        # save most recent tweets
        alltweets.extend(new_tweets)
        
        # update the id of the oldest tweet less one
        oldest = alltweets[-1].id - 1
        
        print(f"...{len(alltweets)} tweets downloaded so far")
    
    #transform the tweepy tweets into a 2D array that will populate the csv 
    outtweets = [[tweet.id_str, tweet.created_at, tweet.full_text, tweet.favorite_count, tweet.retweet_count] for tweet in alltweets]
    
    #write the csv  
    with open(f'new_{screen_name}_tweets.csv', 'w') as f:
        writer = csv.writer(f)
        writer.writerow(["id","created_at","text", "favorites", "retweets"])
        writer.writerows(outtweets)
    
    pass

In [6]:
get_all_tweets(jacobin_handle)

getting tweets before 1371940587935567881
...400 tweets downloaded so far
getting tweets before 1369837983923396607
...600 tweets downloaded so far
getting tweets before 1368041144668610560
...800 tweets downloaded so far
getting tweets before 1365869332815831043
...1000 tweets downloaded so far
getting tweets before 1363877458240544769
...1200 tweets downloaded so far
getting tweets before 1361574533271011327
...1400 tweets downloaded so far
getting tweets before 1359019198043705343
...1600 tweets downloaded so far
getting tweets before 1356750496850182145
...1800 tweets downloaded so far
getting tweets before 1354566206745882623
...2000 tweets downloaded so far
getting tweets before 1352361237892526094
...2200 tweets downloaded so far
getting tweets before 1350382286072471552
...2400 tweets downloaded so far
getting tweets before 1348343298805686273
...2600 tweets downloaded so far
getting tweets before 1345768089678299135
...2800 tweets downloaded so far
getting tweets before 1342817437880877058
...3000 tweets downloaded so far
getting tweets before 1340326025046020097
...3200 tweets downloaded so far
getting tweets before 1338475367267491841
...3202 tweets downloaded so far
getting tweets before 1338438585247121407
...3202 tweets downloaded so far

In [7]:
jacobin_tweets_df = pd.read_csv("new_jacobinmag_tweets.csv")

In [8]:
jacobin_tweets_df

,id,created_at,text,favorites,retweets
0,1374030443897614338,2021-03-22 16:09:20,The recent scandals have exposed liberal darli...,29,5
1,1374019592599789573,2021-03-22 15:26:13,With sexist dress codes and personal harassmen...,60,12
2,1374012998382100487,2021-03-22 15:00:01,As part of an all-out war on oppositional forc...,29,15
3,1374002167435132928,2021-03-22 14:16:59,Turkish president Recep Tayyip Erdoğan and his...,85,29
4,1373990345021657092,2021-03-22 13:30:00,Ken Burns's new docuseries on Ernest Hemingway...,61,17
...,...,...,...,...,...
3197,1338489445012688901,2020-12-14 14:22:06,Billionaire Blackstone CEO Steve Schwarzman br...,84,29
3198,1338484803688144898,2020-12-14 14:03:39,RT @tribunemagazine: India's government is try...,0,103
3199,1338475367267491842,2020-12-14 13:26:09,Today is the 12th anniversary of a heroic act ...,37098,7898
3200,1338453684590678017,2020-12-14 12:00:00,The battle against the Sicilian Mafia wasn't w...,203,35
3201,1338438585247121408,2020-12-14 11:00:00,"Today in 1918, Constance Markievicz became the...",208,31

In [10]:
get_all_tweets(verso_handle)

getting tweets before 1370052523382485000
...398 tweets downloaded so far
getting tweets before 1366325626144239615
...596 tweets downloaded so far
getting tweets before 1351560344733417474
...794 tweets downloaded so far
getting tweets before 1345392153493704703
...993 tweets downloaded so far
getting tweets before 1338534358450380800
...1191 tweets downloaded so far
getting tweets before 1334137359269564422
...1390 tweets downloaded so far
getting tweets before 1329765947587039232
...1590 tweets downloaded so far
getting tweets before 1325786993461256191
...1790 tweets downloaded so far
getting tweets before 1322634950538088453
...1990 tweets downloaded so far
getting tweets before 1321095770209165312
...2189 tweets downloaded so far
getting tweets before 1319215564544528386
...2387 tweets downloaded so far
getting tweets before 1317052020692574208
...2584 tweets downloaded so far
getting tweets before 1314537025811427327
...2783 tweets downloaded so far
getting tweets before 1311309368848244739
...2980 tweets downloaded so far
getting tweets before 1308924609585012735
...3180 tweets downloaded so far
getting tweets before 1306157727673090048
...3231 tweets downloaded so far
getting tweets before 1305542826218852351
...3231 tweets downloaded so far

In [12]:
verso_tweets_df = pd.read_csv("new_versobooks_tweets.csv")

In [13]:
verso_tweets_df

,id,created_at,text,favorites,retweets
0,1373996705536966656,2021-03-22 13:55:16,https://t.co/9u9A5i8160 https://t.co/zEe0noQh31,3,0
1,1373996700495441923,2021-03-22 13:55:15,https://t.co/CfgX6n1sHp,5,1
2,1373996694111670276,2021-03-22 13:55:14,https://t.co/yYTq3sJSYR,1,0
3,1373996689246281729,2021-03-22 13:55:12,https://t.co/EZSaDM0i7I,4,1
4,1373991602763481092,2021-03-22 13:35:00,FREE EBOOK: we've made Feminist City by @Lelly...,26,12
...,...,...,...,...,...
3226,1305604661198696448,2020-09-14 20:29:42,RT @revsoc21: Global capitalism is on a highwa...,0,5
3227,1305556872171323393,2020-09-14 17:19:49,How do we understand calls to defund the polic...,8,6
3228,1305555465485594627,2020-09-14 17:14:13,RT @ReclaimJustice: we can build a different w...,0,19
3229,1305549872569946114,2020-09-14 16:52:00,"To celebrate Verso's 50th Anniversary, we pres...",16,0
3230,1305542826218852352,2020-09-14 16:24:00,"New Review of ""The Feminist and the Sex Offend...",3,0

In [14]:
get_all_tweets(tribune_handle)

getting tweets before 1369693948764168194
...395 tweets downloaded so far
getting tweets before 1365399515419860994
...588 tweets downloaded so far
getting tweets before 1359519438614261760
...783 tweets downloaded so far
getting tweets before 1352295009907843071
...979 tweets downloaded so far
getting tweets before 1347293563877527554
...1175 tweets downloaded so far
getting tweets before 1340740306841513987
...1372 tweets downloaded so far
getting tweets before 1329458086709489667
...1567 tweets downloaded so far
getting tweets before 1317798186807951360
...1760 tweets downloaded so far
getting tweets before 1311031256298254336
...1957 tweets downloaded so far
getting tweets before 1297121224292798468
...2153 tweets downloaded so far
getting tweets before 1286337314654912513
...2349 tweets downloaded so far
getting tweets before 1274379021883789315
...2546 tweets downloaded so far
getting tweets before 1263398377720512514
...2744 tweets downloaded so far
getting tweets before 1252695622077030399
...2942 tweets downloaded so far
getting tweets before 1241403607473442820
...3139 tweets downloaded so far
getting tweets before 1228696909298241536
...3185 tweets downloaded so far
getting tweets before 1226630575303331839
...3185 tweets downloaded so far

In [15]:
tribune_tweets_df = pd.read_csv("new_tribunemagazine_tweets.csv")

In [16]:
tribune_tweets_df

,id,created_at,text,favorites,retweets
0,1374025565200601090,2021-03-22 15:49:57,"The Paris Commune, which began 150 years ago t...",75,32
1,1374019515378499586,2021-03-22 15:25:55,RT @Stewfsmith: A pleasure to go deep on Willi...,0,11
2,1374007257776656390,2021-03-22 14:37:12,"RT @tribunemagazine: In Thurrock, the local To...",0,134
3,1373976842433146893,2021-03-22 12:36:21,"Across the world, government promises of a 'gr...",81,20
4,1373962628872085509,2021-03-22 11:39:52,RT @curiousvolumes: 'To quote one of the binme...,0,14
...,...,...,...,...,...
3180,1226871861130268672,2020-02-10 14:13:40,The disgraceful state of Britain's children's ...,232,98
3181,1226826776330022919,2020-02-10 11:14:31,RT @LabGND: There's no #GreenNewDeal without d...,0,13
3182,1226813627061108736,2020-02-10 10:22:16,"In the 1960s, a group of South African and Bri...",128,58
3183,1226649885853790210,2020-02-09 23:31:37,🕑 THIRTY MINUTES LEFT 🕑\nOn our Tribune subscr...,15,6
3184,1226630575303331840,2020-02-09 22:14:53,RT @ronanburtenshaw: It was great to be able t...,0,39

In [17]:
get_all_tweets(haymarket_handle)

getting tweets before 1371474063839920128
...394 tweets downloaded so far
getting tweets before 1368952343899803648
...589 tweets downloaded so far
getting tweets before 1366225427388317696
...789 tweets downloaded so far
getting tweets before 1364658291549339651
...986 tweets downloaded so far
getting tweets before 1363569785783607295
...1184 tweets downloaded so far
getting tweets before 1361796765830287362
...1382 tweets downloaded so far
getting tweets before 1359597601566375937
...1576 tweets downloaded so far
getting tweets before 1357448081114083327
...1768 tweets downloaded so far
getting tweets before 1356625584252674049
...1965 tweets downloaded so far
getting tweets before 1354823857044152321
...2162 tweets downloaded so far
getting tweets before 1353014244804091903
...2361 tweets downloaded so far
getting tweets before 1351974814752321540
...2560 tweets downloaded so far
getting tweets before 1350094917008306184
...2758 tweets downloaded so far
getting tweets before 1348719832519335943
...2957 tweets downloaded so far
getting tweets before 1346925529304363016
...3153 tweets downloaded so far
getting tweets before 1343308859331510273
...3201 tweets downloaded so far
getting tweets before 1341812366040838143
...3201 tweets downloaded so far

In [18]:
haymarket_tweets_df = pd.read_csv("new_haymarketbooks_tweets.csv")

In [19]:
haymarket_tweets_df.head()

,id,created_at,text,favorites,retweets
0,1374038480012054530,2021-03-22 16:41:16,RT @DavidKaib: The border is the crisis.,0,11
1,1374038291754983425,2021-03-22 16:40:31,RT @JessedHagopian: Do you get it now?\n\nThis...,0,4
2,1374036102831616007,2021-03-22 16:31:49,"RT @angelinachapin: ""One woman told me going t...",0,35
3,1374034653741510664,2021-03-22 16:26:04,RT @PeoplesForumNYC: 1804 Books (https://t.co/...,0,14
4,1374032834424356865,2021-03-22 16:18:50,RT @mcmansionhell: lol it’s an exurb of single...,0,496